version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: belogolov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_db_app
    ports:
      - "5432:5432"

  app:
    container_name: python-app
    build: 
      context: ./python
    depends_on:
      db:
        condition: service_healthy 
    networks:
      - my_db_app
networks:
  my_db_app:
    driver: bridge
volumes:
  db_data:
